//enums.ts
export enum AUTH_ACTIONS {
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    SET_TOKEN = 'SET_TOKEN',
    SET_USER = 'SET_USER',
    SET_LOADING = 'SET_LOADING',
    SET_ASSETS_LOADING = 'SET_ASSETS_LOADING',
    ENTER_RECOVERY = 'ENTER_RECOVERY', 
    EXIT_RECOVERY = 'EXIT_RECOVERY',
}